
CREATE DATABASE EMPRESA 

USE EMPRESA 

CREATE TABLE EMPLEADOS (
    NumEmp SMALLINT NOT NULL,
    nombre VARCHAR(20),
    edad SMALLINT,
    oficina VARCHAR(20),
    puesto VARCHAR(20),
    fecha_contrato DATE,
    jefe VARCHAR(20),
    cuota SMALLINT,
    ventas INT
)
CREATE TABLE CLIENTES (
    NumClie SMALLINT NOT NULL,
    nombre VARCHAR(50),
    resp SMALLINT,
    limitecredito DECIMAL(10, 2)
)
CREATE TABLE OFICINA (
    oficina VARCHAR(20) NOT NULL,
    ciudad VARCHAR(50),
    region VARCHAR(50),
    dir SMALLINT,
    objetivo DECIMAL(10, 2),
    ventas DECIMAL(10, 2)
)
CREATE TABLE PRODUCTOS (
    idfab SMALLINT NOT NULL,
    idproducto SMALLINT NOT NULL,
    descripcion VARCHAR(100),
    precio DECIMAL(10, 2),
    existencias INT
)
CREATE TABLE PEDIDOS (
    numpedido SMALLINT NOT NULL,
    fechapedido DATE,
    clie SMALLINT,
    resp SMALLINT,
    fab SMALLINT,
    producto SMALLINT,
    cant INT,
    importe DECIMAL(10, 2)
)

	ALTER TABLE EMPLEADOS
	   ADD CONSTRAINT PK_EMPLEADOS_NUMEMP PRIMARY KEY (NumEmp),
			CONSTRAINT FK_EMPLEADOS_NUMEMP FOREIGN KEY (NumEmp) REFERENCES EMPLEADOS(NumEmp),
			CONSTRAINT FK_EMPLEADOS_JEFE FOREIGN KEY (jefe) REFERENCES EMPLEADOS(NumEmp);
			

	ALTER TABLE OFICINA
		ADD CONSTRAINT PK_OFICINA_OFICINA PRIMARY KEY (oficina),
        CONSTRAINT FK_OFICINA_OFICINA FOREIGN KEY (oficina) REFERENCES OFICINA(oficina);


	ALTER TABLE CLIENTES
    ADD CONSTRAINT PK_CLIENTE_NUMCLIE PRIMARY KEY (NumClie);


	ALTER TABLE PEDIDOS
		ADD CONSTRAINT PK_PEDIDOS_NUMPEDIDO PRIMARY KEY (numpedido),
			CONSTRAINT FK_PEDIDOS_CLIE FOREIGN KEY (Clie) REFERENCES CLIENTES(NumClie);	
		
	ALTER TABLE PRODUCTOS
		ADD CONSTRAINT FK_PRODUCTOS_IDFAB FOREIGN KEY (idfab) REFERENCES PRODUCTO(idfab),
			CONSTRAINT PK_PRODUCTOS_IDFAB PRIMARY KEY (idfab),
			CONSTRAINT FK_PRODUCTOS_IDPRODUCTO FOREIGN KEY (idproducto) REFERENCES PROFUCTO(idproducto);


	ALTER TABLE EMPLEADOS
		DROP CONSTRAINT PK_EMPLEADOS_NUMEMP,
			CONSTRAINT FK_EMPLEADOS_NUMEMP,
			CONSTRAINT FK_EMPLEADOS_JEFE;


	ALTER TABLE OFICINA
		DROP CONSTRAINT PK_OFICINA_OFICINA,
        CONSTRAINT FK_OFICINA_OFICINA;


	ALTER TABLE CLIENTES
		 DROP CONSTRAINT PK_CLIENTE_NUMCLIE;


	ALTER TABLE PEDIDOS
		DROP CONSTRAINT PK_PEDIDOS_NUMPEDIDO,
			CONSTRAINT FK_PEDIDOS_CLIE;


	ALTER TABLE PRODUCTOS
		DROP CONSTRAINT FK_PRODUCTOS_IDFAB,
			 CONSTRAINT PK_PRODUCTOS_IDFAB,
			 CONSTRAINT FK_PRODUCTOS_IDPRODUCTO;


	ALTER TABLE EMPLEADOS
		ADD SUELDOS INT NOT NULL;

	ALTER TABLE CLIENTE 
		ADD Cuenta_Bancaria varchar(20);

	ALTER TABLE PRODUCTOS
		ADD Color VARCHAR(10);

	ALTER TABLE EMPLEADOS
		ALTER COLUMN SUELDOS DECIMAL(3,1) NOT NULL;

	ALTER TABLE CLIENTE 
		ALTER COLUMN Cuenta_Bancaria varchar(50);

	ALTER TABLE PRODUCTOS
		ALTER COLUMN Color DECIMAL(4,1);
