DROP DATABASE IF EXISTS COMER

CREATE DATABASE COMER

USE COMER

CREATE TABLE COMIDA (
FRUTA VARCHAR(10) CONSTRAINT PK_COMIDA PRIMARY KEY,
VERDURA VARCHAR(10) CHECK(VERDURA NOT LIKE '%[0-9]%'),
CARNE CHAR
)
CREATE TABLE COME (
DNI CHAR(9) CONSTRAINT PK_COME PRIMARY KEY CHECK(DNI LIKE '%[0-9]%'),
FRUTA VARCHAR(10),
VERDURA VARCHAR(10),
CARNE CHAR,
CONSTRAINT FK_COME_COMIDA_FRUTA FOREIGN KEY (FRUTA) REFERENCES COMIDA(FRUTA),
CONSTRAINT UQ_COME_COMIDA_CARNE UNIQUE (CARNE) REFERENCES COMIDA(CARNE)
)

SELECT * FROM COME
SELECT * FROM COMIDA

INSERT INTO COMIDA(FRUTA) VALUES ('BANANA');

DELETE FROM COME WHERE DNI = ('295197833');

ALTER TABLE COME
	ADD CONSTRAINT CK_VERDURA CHECK(VERDURA IN ('A','B')),
		CONSTRAINT CK_FRUTA CHECK(FRUTA LIKE ('%[0-9]%'));
	