-----------TABLA EMPLEADOS----------

CREATE DATABASE Empleados

USE Empleados

CREATE TABLE EMPLEADO (
	DNI VARCHAR(9) Not Null Constraint PKEMPLEADO PRIMARY KEY
	)
CREATE TABLE DEPARTAMENTO (
	NUMDEPAR SMALLINT Not Null Constraint PKDEPARTAMENTO PRIMARY KEY
	)
CREATE TABLE TRABAJA (
	PKDEPARTAMENTO SMALLINT NOT NULL,
    PKEMPLEADO VARCHAR(9) NOT NULL,
    CONSTRAINT PKTRABAJA PRIMARY KEY (PKDEPARTAMENTO, PKEMPLEADO),
    CONSTRAINT FK_TRABAJA_DEPARTAMENTO FOREIGN KEY (PKDEPARTAMENTO) REFERENCES DEPARTAMENTO(NUMDEPAR),
    CONSTRAINT FK_TRABAJA_EMPLEADO FOREIGN KEY (PKEMPLEADO) REFERENCES EMPLEADO(DNI)
	)

	-----------TABLA JUEGA----------

	CREATE DATABASE JUEGA

	USE JUEGA

	CREATE TABLE FUTBOLISTA (
		DNI VARCHAR(9) Not Null Constraint PKFUTBOLISTA PRIMARY KEY
		)
	CREATE TABLE PARTIDO (
		ID SMALLINT Not Null Constraint PKPARTIDO PRIMARY KEY,
		FECHA SmallDateTime Not Null
		)
	create table juega (
		PKFUTBOLISTA VARCHAR(9) NOT NULL,
		PKPARTIDO SMALLINT NOT NULL,
		CONSTRAINT PKJUEGA PRIMARY KEY (PKFUTBOLISTA, PKPARTIDO),
		CONSTRAINT FK_JUEGA_FUTBOLISTA FOREIGN KEY (PKFUTBOLISTA) REFERENCES FUTBOLISTA(DNI),
		CONSTRAINT FK_JUEGA_PARTIDO FOREIGN KEY (PKPARTIDO) REFERENCES PARTIDO(ID)
		)

	-----------TABLA COMPRA----------

	CREATE DATABASE COMPRA

	USE COMPRA

	CREATE TABLE CLIENTE (
	DNI VARCHAR(9) Not Null Constraint PKCLIENTE PRIMARY KEY
	)
	CREATE TABLE TRAJE (
	MODELO SMALLINT Not Null Constraint PKTRAJE PRIMARY KEY
	)
	CREATE TABLE COMPRA (
		PKCLIENTE VARCHAR(9) NOT NULL,
		PKTRAJE SMALLINT NOT NULL,
		CONSTRAINT PKCOMPRA PRIMARY KEY (PKCLIENTE, PKTRAJE),
		CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (PKCLIENTE) REFERENCES CLIENTE(DNI),
		CONSTRAINT FK_COMPRA_TRAJE FOREIGN KEY (PKTRAJE) REFERENCES TRAJE(MODELO)
		)

	-----------TABLA COMPRA----------

	CREATE DATABASE TIENE

	USE TIENE

	CREATE TABLE PERSONA (
	DNI CHAR(9) NOT NULL CONSTRAINT PKPERSONA PRIMARY KEY 
	)
	CREATE TABLE COCHE (
	MATRICULA CHAR(7) NOT NULL CONSTRAINT PKCOCHE PRIMARY KEY,
	COLOR VARCHAR(15) NOT NULL
	)
	CREATE TABLE TIENE (
	PKPERSONA CHAR(9) NOT NULL,
	PKCOCHE CHAR(7),
	CONSTRAINT PKTIENE PRIMARY KEY (PKCOCHE),
	CONSTRAINT FK_TIENE_COCHE FOREIGN KEY (PKCOCHE) REFERENCES COCHE(MATRICULA),
	CONSTRAINT FK_TIENE_PERSONA FOREIGN KEY (PKPERSONA) REFERENCES PERSONA(DNI)
	)

	-----------TABLA POSEE----------

	CREATE DATABASE POSEE

	USE POSEE

	CREATE TABLE PERSONA (
	Dni Char(9) Not Null Constraint PKPERSONA Primary key
	)
	CREATE TABLE COCHE (
	Matricula Char(7) Not Null Constraint PKCOCHE Primary key,
	Color Varchar(15) Not Null
	)
	CREATE TABLE POSEE (
	PKPERSONA Char(9) Not Null,
	PKCOCHE Char(7) Not Null,
	FECHA SmallDateTime Not Null,
	CONSTRAINT FK_POSEE_PERSONA FOREIGN KEY (PKPERSONA) REFERENCES PERSONA(Dni),
	CONSTRAINT FK_POSEE_COCHE FOREIGN KEY (PKCOCHE) REFERENCES COCHE(Matricula)
	)

		-----------TABLA GUARDA----------

	CREATE DATABASE GUARDA

	USE GUARDA

	CREATE TABLE COCHE (
	Matricula char(7) Not Null Constraint PK_COCHE Primary Key
	)
	CREATE TABLE COCHERA (
	Id SmallInt Not Null Constraint PK_COCHERA Primary Key
	)
	CREATE TABLE GUARDA (
	PK_COCHE char(7) Not Null,
	PK_COCHERA SmallInt Not Null,
	CONSTRAINT PK_GUARDA PRIMARY KEY (PK_COCHE),
	CONSTRAINT FK_GUARDA_COCHE FOREIGN KEY (PK_COCHE) REFERENCES COCHE(Matricula),
	CONSTRAINT UQ_GUARDA_COCHERA UNIQUE (PK_COCHERA),
	CONSTRAINT FK_GUARDA_COCHERA FOREIGN KEY (PK_COCHERA) REFERENCES COCHERA(Id)
	)

		-----------TABLA Ej10----------

		CREATE DATABASE ESCUELA

		USE ESCUELA

		CREATE TABLE ALUMNO (
			DNI CHAR(9) CONSTRAINT PK_ALUMNO PRIMARY KEY
		)

		CREATE TABLE ORDENADOR (
			ID INT CONSTRAINT PK_ORDENADOR PRIMARY KEY
		)

		CREATE TABLE AULA (
			NUMERO INT CONSTRAINT PK_AULA PRIMARY KEY
		)

		CREATE TABLE UTILIZA (
			DNI CHAR(9),
			ORDENADOR INT,
			CURSO VARCHAR(50),
			CONSTRAINT PK_UTILIZA PRIMARY KEY (DNI, ORDENADOR, CURSO),
			CONSTRAINT FK_UTILIZA_ALUMNO FOREIGN KEY (DNI) REFERENCES ALUMNO(DNI),
			CONSTRAINT FK_UTILIZA_ORDENADOR FOREIGN KEY (ORDENADOR) REFERENCES ORDENADOR(ID)
		)

		CREATE TABLE ESTA (
			ORDENADOR INT,
			AULA INT,
			CURSO VARCHAR(50),
			CONSTRAINT PK_ESTA PRIMARY KEY (ORDENADOR, AULA, CURSO),
			CONSTRAINT FK_ESTA_ORDENADOR FOREIGN KEY (ORDENADOR) REFERENCES ORDENADOR(ID),
			CONSTRAINT FK_ESTA_AULA FOREIGN KEY (AULA) REFERENCES AULA(NUMERO)
		)

		
		-----------TABLA Ej11----------

		CREATE DATABASE GESTION_ORDENADORES

		USE GESTION_ORDENADORES

		CREATE TABLE ALUMNO (
			DNI CHAR(9) CONSTRAINT PK_ALUMNO PRIMARY KEY
		)

		CREATE TABLE ORDENADOR (
			ID INT CONSTRAINT PK_ORDENADOR PRIMARY KEY
		)

		CREATE TABLE APLICACION (
			TITULO VARCHAR(100) CONSTRAINT PK_APLICACION PRIMARY KEY
		)

		CREATE TABLE UTILIZA (
			ALUMNO CHAR(9),
			ORDENADOR INT,
			APLICACION VARCHAR(100),
			TIEMPO INT,
			CONSTRAINT PK_UTILIZA PRIMARY KEY (ALUMNO, ORDENADOR, APLICACION),
			CONSTRAINT FK_UTILIZA_ALUMNO FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(DNI),
			CONSTRAINT FK_UTILIZA_ORDENADOR FOREIGN KEY (ORDENADOR) REFERENCES ORDENADOR(ID),
			CONSTRAINT FK_UTILIZA_APLICACION FOREIGN KEY (APLICACION) REFERENCES APLICACION(TITULO)
		)

		
		-----------TABLA Ej12----------

		CREATE DATABASE TRANSPORTE

		USE TRANSPORTE

		CREATE TABLE CALLE (
		NOMBRE VARCHAR(100) NOT NULL CONSTRAINT PK_CALLE PRIMARY KEY
		)
		CREATE TABLE CONDUCTOR (
		DNI CHAR(9) NOT NULL CONSTRAINT PK_CONDUCTOR PRIMARY KEY,
		PK_CALLE VARCHAR(100) NOT NULL,
		CONSTRAINT FK_CONDUCTOR_CALLE FOREIGN KEY (PK_CALLE) REFERENCES CALLE(NOMBRE)
		)
		CREATE TABLE AUTOBUS (
		MATRICULA CHAR(7) NOT NULL CONSTRAINT PK_AUTOBUS PRIMARY KEY
		)
		CREATE TABLE LINEA (
		NUMERO INT NOT NULL CONSTRAINT PK_LINEA PRIMARY KEY
		)
		CREATE TABLE UTILIZA (
		PK_CONDUCTOR CHAR(9) NOT NULL,
		PK_AUTOBUS CHAR(7) NOT NULL,
		PK_LINEA INT NOT NULL,
		DIA DATE NOT NULL,
		CONSTRAINT PK_UTILIZA PRIMARY KEY (PK_CONDUCTOR, PK_AUTOBUS, PK_LINEA, DIA),
		CONSTRAINT FK_UTILIZA_CONDUCTOR FOREIGN KEY (PK_CONDUCTOR) REFERENCES CONDUCTOR(DNI),
		CONSTRAINT FK_UTILIZA_AUTOBUS FOREIGN KEY (PK_AUTOBUS) REFERENCES AUTOBUS(MATRICULA),
		CONSTRAINT FK_UTILIZA_LINEA FOREIGN KEY (PK_LINEA) REFERENCES LINEA(NUMERO)
		)
		CREATE TABLE PASA (
		PK_LINEA INT NOT NULL,
		PK_CALLE VARCHAR(100) NOT NULL,
		CONSTRAINT PK_PASA PRIMARY KEY (PK_LINEA, PK_CALLE),
		CONSTRAINT FK_PASA_LINEA FOREIGN KEY (PK_LINEA) REFERENCES LINEA(NUMERO),
		CONSTRAINT FK_PASA_CALLE FOREIGN KEY (PK_CALLE) REFERENCES CALLE(NOMBRE)
		)

		-----------TABLA Ej13----------

		CREATE DATABASE EDIFICIOS

		USE EDIFICIOS

		CREATE TABLE EDIFICIO (
		NOMBRE VARCHAR(100) NOT NULL CONSTRAINT PK_EDIFICIO PRIMARY KEY,
		DIRECCION VARCHAR(200) NOT NULL
		)
		CREATE TABLE EMPRESA (
		CIF CHAR(9) NOT NULL CONSTRAINT PK_EMPRESA PRIMARY KEY,
		NOMBRE VARCHAR(100) NOT NULL
		)
		CREATE TABLE OFICINAS (
		PK_EDIFICIO VARCHAR(100) NOT NULL,
		NUMERO INT NOT NULL,
		PK_EMPRESA CHAR(9) NOT NULL,
		CONSTRAINT PK_OFICINAS PRIMARY KEY (PK_EDIFICIO, NUMERO),
		CONSTRAINT FK_OFICINAS_EDIFICIO FOREIGN KEY (PK_EDIFICIO) REFERENCES EDIFICIO(NOMBRE)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
		CONSTRAINT FK_OFICINAS_EMPRESA FOREIGN KEY (PK_EMPRESA) REFERENCES EMPRESA(CIF)
		)

		-----------TABLA Ej14----------

		CREATE DATABASE PROYECTOS

		USE PROYECTOS

		CREATE TABLE EDIFICIO (
		NOMBRE VARCHAR(100) Constraint PK_EDIFICIO Primary Key,
		DIRECCION VARCHAR(200) NOT NULL
		)

		CREATE TABLE OFICINA (
		PK_EDIFICIO VARCHAR(100) NOT NULL,
		NUMERO INT NOT NULL,
		Constraint PK_OFICINA Primary Key (PK_EDIFICIO, NUMERO),
		Constraint FK_OFICINA_EDIFICIO FOREIGN KEY (PK_EDIFICIO) REFERENCES EDIFICIO(NOMBRE)
		)

		CREATE TABLE OBRA (
		ID INT Constraint PK_OBRA Primary Key
		)

		CREATE TABLE EMPLEADO_OFICINISTA (
		DNI CHAR(9) Constraint PK_EMPLEADO_OFICINISTA Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		SUELDO DECIMAL(10, 2) NOT NULL,
		TITULACION VARCHAR(100) NOT NULL,
		PK_EDIFICIO VARCHAR(100) NOT NULL,
		PK_OFICINA INT NOT NULL,
		JEFE CHAR(9),
		Constraint FK_OFICINISTA_OFICINA FOREIGN KEY (PK_EDIFICIO, PK_OFICINA) REFERENCES OFICINA(PK_EDIFICIO, NUMERO),
		Constraint FK_OFICINISTA_JEFE FOREIGN KEY (JEFE) REFERENCES EMPLEADO_OFICINISTA(DNI)
		)

		CREATE TABLE EMPLEADO_OBRERO (
		DNI CHAR(9) Constraint PK_EMPLEADO_OBRERO Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		SUELDO DECIMAL(10, 2) NOT NULL,
		PK_OBRA INT NOT NULL,
		FECHA_INICIO DATE NOT NULL,
		JEFE CHAR(9),
		Constraint FK_OBRERO_OBRA FOREIGN KEY (PK_OBRA) REFERENCES OBRA(ID),
		Constraint FK_OBRERO_JEFE FOREIGN KEY (JEFE) REFERENCES EMPLEADO_OBRERO(DNI)
		)

		-----------TABLA Ej15----------

		CREATE DATABASE INSTITUTO

		USE INSTITUTO

		CREATE TABLE ASIGNATURA (
		COD_ASIG INT Constraint PK_ASIGNATURA Primary Key
		)

		CREATE TABLE ESTUDIO (
		COD_ESTUDIO INT Constraint PK_ESTUDIO Primary Key
		)

		CREATE TABLE ASIGNATURA_ESTUDIO (
		COD_ASIG INT NOT NULL,
		COD_ESTUDIO INT NOT NULL,
		Constraint PK_ASIGNATURA_ESTUDIO Primary Key (COD_ASIG, COD_ESTUDIO),
		Constraint FK_ASIGNATURA_ESTUDIO_ASIGNATURA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG),
		Constraint FK_ASIGNATURA_ESTUDIO_ESTUDIO FOREIGN KEY (COD_ESTUDIO) REFERENCES ESTUDIO(COD_ESTUDIO)
		)

		CREATE TABLE EXPEDIENTE (
		NUM_REG INT Constraint PK_EXPEDIENTE Primary Key,
		ALUMNO CHAR(9) NOT NULL,
		Constraint FK_EXPEDIENTE_ALUMNO FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(DNI)
		)

		CREATE TABLE FICHA (
		NUM_REG INT NOT NULL,
		COD_ASIG INT NOT NULL,
		CURSO INT NOT NULL,
		JUNIO DECIMAL(5, 2),
		SEPTIEMBRE DECIMAL(5, 2),
		Constraint PK_FICHA Primary Key (NUM_REG, COD_ASIG, CURSO),
		Constraint FK_FICHA_EXPEDIENTE FOREIGN KEY (NUM_REG) REFERENCES EXPEDIENTE(NUM_REG),
		Constraint FK_FICHA_ASIGNATURA FOREIGN KEY (COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
		)

		CREATE TABLE GRUPO (
		COD_GRUPO INT Constraint PK_GRUPO Primary Key
		)

		CREATE TABLE PROFESOR (
		NRP CHAR(9) Constraint PK_PROFESOR Primary Key,
		HORA_ALUMN INT NOT NULL,
		HORA_PADRES INT NOT NULL,
		SEMINARIO INT NOT NULL,
		Constraint FK_PROFESOR_SEMINARIO FOREIGN KEY (SEMINARIO) REFERENCES SEMINARIO(COD_SEMINARIO)
		)

		CREATE TABLE IMPARTE (
		ASIGNATURA INT NOT NULL,
		PROFESOR CHAR(9) NOT NULL,
		GRUPO INT NOT NULL,
		Constraint PK_IMPARTE Primary Key (ASIGNATURA, PROFESOR, GRUPO),
		Constraint FK_IMPARTE_ASIGNATURA FOREIGN KEY (ASIGNATURA) REFERENCES ASIGNATURA(COD_ASIG),
		Constraint FK_IMPARTE_PROFESOR FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(NRP),
		Constraint FK_IMPARTE_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO(COD_GRUPO)
		)

		CREATE TABLE TUTORIA (
		PROFESOR CHAR(9) NOT NULL,
		ALUMNO CHAR(9) NOT NULL,
		FECHA DATE NOT NULL,
		Constraint PK_TUTORIA Primary Key (PROFESOR, ALUMNO, FECHA),
		Constraint FK_TUTORIA_PROFESOR FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(NRP),
		Constraint FK_TUTORIA_ALUMNO FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(DNI)
		)

		CREATE TABLE SEMINARIO (
		COD_SEMINARIO INT Constraint PK_SEMINARIO Primary Key,
		JEFE CHAR(9) NOT NULL,
		Constraint FK_SEMINARIO_JEFE FOREIGN KEY (JEFE) REFERENCES PROFESOR(NRP)
		)

		CREATE TABLE ALUMNO (
		DNI CHAR(9) Constraint PK_ALUMNO Primary Key,
		COD_ESTUDIO INT NOT NULL,
		EXPEDIENTE INT NOT NULL,
		GRUPO INT NOT NULL,
		Constraint FK_ALUMNO_ESTUDIO FOREIGN KEY (COD_ESTUDIO) REFERENCES ESTUDIO(COD_ESTUDIO),
		Constraint FK_ALUMNO_EXPEDIENTE FOREIGN KEY (EXPEDIENTE) REFERENCES EXPEDIENTE(NUM_REG),
		Constraint FK_ALUMNO_GRUPO FOREIGN KEY (GRUPO) REFERENCES GRUPO(COD_GRUPO)
		)

		CREATE TABLE TUTOR_LEGAL (
		DNI_ALUMNO CHAR(9) NOT NULL,
		DNI_TUTOR CHAR(9) NOT NULL,
		Constraint PK_TUTOR_LEGAL Primary Key (DNI_ALUMNO, DNI_TUTOR),
		Constraint FK_TUTOR_LEGAL_ALUMNO FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO(DNI),
		Constraint FK_TUTOR_LEGAL_TUTOR FOREIGN KEY (DNI_TUTOR) REFERENCES TUTOR_LEGAL(DNI_TUTOR)
		)

		-----------TABLA Ej16----------

		CREATE DATABASE CAPACITACION

		USE CAPACITACION

		CREATE TABLE EMPLEADO (
		COD_EMPLEADO INT Constraint PK_EMPLEADO Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		APELLIDOS VARCHAR(100) NOT NULL,
		NIF CHAR(9) NOT NULL,
		DIRECCION VARCHAR(200),
		TELEFONO CHAR(15),
		SALARIO DECIMAL(10, 2) NOT NULL
		)

		CREATE TABLE CAPACITADO (
		COD_EMPLEADO INT Constraint PK_CAPACITADO Primary Key,
		COD_CURSO INT NOT NULL,
		Constraint FK_CAPACITADO_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
		Constraint FK_CAPACITADO_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)
		)

		CREATE TABLE NO_CAPACITADO (
		COD_EMPLEADO INT Constraint PK_NO_CAPACITADO Primary Key,
		COD_CURSO INT NOT NULL,
		Constraint FK_NO_CAPACITADO_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
		Constraint FK_NO_CAPACITADO_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)
		)

		CREATE TABLE RECIBE (
		COD_EMPLEADO INT NOT NULL,
		COD_CURSO INT NOT NULL,
		FECHA_CURSO DATE NOT NULL,
		Constraint PK_RECIBE Primary Key (COD_EMPLEADO, COD_CURSO, FECHA_CURSO),
		Constraint FK_RECIBE_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
		Constraint FK_RECIBE_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)
		)

		CREATE TABLE EDICION (
		ID_EDICION INT Constraint PK_EDICION Primary Key,
		COD_CURSO INT NOT NULL,
		FECHA DATE NOT NULL,
		LUGAR VARCHAR(200) NOT NULL,
		HORARIO VARCHAR(50) NOT NULL,
		Constraint FK_EDICION_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)
		)

		CREATE TABLE CURSO (
		COD_CURSO INT Constraint PK_CURSO Primary Key,
		NOMBRE VARCHAR(200) NOT NULL,
		DESCRIPCION VARCHAR(500)
		)

		CREATE TABLE IMPARTE (
		ID_EDICION INT NOT NULL,
		COD_EMPLEADO INT NOT NULL,
		Constraint PK_IMPARTE Primary Key (ID_EDICION, COD_EMPLEADO),
		Constraint FK_IMPARTE_EDICION FOREIGN KEY (ID_EDICION) REFERENCES EDICION(ID_EDICION),
		Constraint FK_IMPARTE_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO)
		)

		-----------TABLA Ej17----------

		CREATE DATABASE MUNICIPIO_VIVIENDA

		USE MUNICIPIO_VIVIENDA

		CREATE TABLE PERSONA (
		DNI CHAR(9) Constraint PK_PERSONA Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		APELLIDOS VARCHAR(100) NOT NULL,
		EDAD INT NOT NULL,
		EMPADRONADA CHAR(5),
		CALLE VARCHAR(100),
		NUMERO INT,
		CP CHAR(5),
		CABEZA_FAMILIA CHAR(9),
		Constraint FK_PERSONA_MUNICIPIO FOREIGN KEY (EMPADRONADA) REFERENCES MUNICIPIO(CP),
		Constraint FK_PERSONA_VIVIENDA FOREIGN KEY (CALLE, NUMERO, CP) REFERENCES VIVIENDA(CALLE, NUMERO, CP),
		Constraint FK_PERSONA_CABEZA_FAMILIA FOREIGN KEY (CABEZA_FAMILIA) REFERENCES PERSONA(DNI)
		)

		CREATE TABLE MUNICIPIO (
		CP CHAR(5) Constraint PK_MUNICIPIO Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		POBLACION INT NOT NULL
		)

		CREATE TABLE VIVIENDA (
		CALLE VARCHAR(100),
		NUMERO INT,
		CP CHAR(5),
		TIPO VARCHAR(50),
		Constraint PK_VIVIENDA Primary Key (CALLE, NUMERO, CP),
		Constraint FK_VIVIENDA_MUNICIPIO FOREIGN KEY (CP) REFERENCES MUNICIPIO(CP)
		)

		CREATE TABLE PROPIETARIA (
		DNI CHAR(9),
		CALLE VARCHAR(100),
		NUMERO INT,
		CP CHAR(5),
		Constraint PK_PROPIETARIA Primary Key (DNI, CALLE, NUMERO, CP),
		Constraint FK_PROPIETARIA_PERSONA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
		Constraint FK_PROPIETARIA_VIVIENDA FOREIGN KEY (CALLE, NUMERO, CP) REFERENCES VIVIENDA(CALLE, NUMERO, CP)
		)

		-----------TABLA Ej18----------

		CREATE DATABASE AREA_CURSO

		USE AREA_CURSO

		CREATE TABLE AREA (
		CODAREA CHAR(5) Constraint PK_AREA Primary Key,
		NOMBRE VARCHAR(100) NOT NULL
		)

		CREATE TABLE SEDE (
		CODSEDE CHAR(5) Constraint PK_SEDE Primary Key,
		NOMBRE VARCHAR(100) NOT NULL
		)

		CREATE TABLE PROFESOR (
		DNI CHAR(9) Constraint PK_PROFESOR Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		APELLIDOS VARCHAR(100) NOT NULL,
		ENCARGA CHAR(5),
		SEDE CHAR(5),
		Constraint FK_PROFESOR_AREA FOREIGN KEY (ENCARGA) REFERENCES AREA(CODAREA),
		Constraint FK_PROFESOR_SEDE FOREIGN KEY (SEDE) REFERENCES SEDE(CODSEDE)
		)

		CREATE TABLE ALUMNO (
		DNI CHAR(9) Constraint PK_ALUMNO Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		APELLIDOS VARCHAR(100) NOT NULL
		)

		CREATE TABLE COORDINADOR (
		DNI CHAR(9) Constraint PK_COORDINADOR Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		APELLIDOS VARCHAR(100) NOT NULL
		)

		CREATE TABLE CURSO (
		CODCURSO CHAR(5) Constraint PK_CURSO Primary Key,
		NOMBRE VARCHAR(100) NOT NULL,
		AREA CHAR(5),
		COORDINADOR CHAR(9),
		DIRIGIDO CHAR(9),
		Constraint FK_CURSO_AREA FOREIGN KEY (AREA) REFERENCES AREA(CODAREA),
		Constraint FK_CURSO_COORDINADOR FOREIGN KEY (COORDINADOR) REFERENCES COORDINADOR(DNI),
		Constraint FK_CURSO_DIRIGIDO FOREIGN KEY (DIRIGIDO) REFERENCES COORDINADOR(DNI)
		)

		CREATE TABLE AREAPROFESOR (
		AREA CHAR(5),
		PROFESOR CHAR(9),
		Constraint PK_AREAPROFESOR Primary Key (AREA, PROFESOR),
		Constraint FK_AREAPROFESOR_AREA FOREIGN KEY (AREA) REFERENCES AREA(CODAREA),
		Constraint FK_AREAPROFESOR_PROFESOR FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(DNI)
		)

		CREATE TABLE AREASEDE (
		AREA CHAR(5),
		SEDE CHAR(5),
		Constraint PK_AREASEDE Primary Key (AREA, SEDE),
		Constraint FK_AREASEDE_AREA FOREIGN KEY (AREA) REFERENCES AREA(CODAREA),
		Constraint FK_AREASEDE_SEDE FOREIGN KEY (SEDE) REFERENCES SEDE(CODSEDE)
		)

		CREATE TABLE MATRICULA (
		CURSO CHAR(5),
		ALUMNO CHAR(9),
		Constraint PK_MATRICULA Primary Key (CURSO, ALUMNO),
		Constraint FK_MATRICULA_CURSO FOREIGN KEY (CURSO) REFERENCES CURSO(CODCURSO),
		Constraint FK_MATRICULA_ALUMNO FOREIGN KEY (ALUMNO) REFERENCES ALUMNO(DNI)
		)

		CREATE TABLE PROFESORCURSO (
		PROFESOR CHAR(9),
		CURSO CHAR(5),
		Constraint PK_PROFESORCURSO Primary Key (PROFESOR, CURSO),
		Constraint FK_PROFESORCURSO_PROFESOR FOREIGN KEY (PROFESOR) REFERENCES PROFESOR(DNI),
		Constraint FK_PROFESORCURSO_CURSO FOREIGN KEY (CURSO) REFERENCES CURSO(CODCURSO)
		)



		CREATE DATABASE OFICINAS

		USE OFICINAS

		CREATE TABLE EDIFICIO (
		NOMBRE VARCHAR(30) Not Null CONSTRAINT FK_EDIFICIO PRIMARY KEY,
		DIRECCION VARCHAR(40)
		)
		CREATE TABLE EMPRESA (
		CIF CHAR(8) Not Null CONSTRAINT PK_EMPRESA PRIMARY KEY,
		NOMBRE VARCHAR(30)
		)
		CREATE TABLE OFICINA (
		NUMERO CHAR(3),
		CIF CHAR(8),
		NOMBRE VARCHAR(30),
		CONSTRAINT PK_OFICINA PRIMARY KEY (NUMERO, NOMBRE),
		CONSTRAINT FK_OFICINA_EMPRESA FOREIGN KEY (CIF) REFERENCES EMPRESA(CIF)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
		CONSTRAINT FK_OFICINA_EDIFICIO FOREIGN KEY (NOMBRE) REFERENCES EDIFICIO(NOMBRE)
		ON DELETE CASCADE
		ON UPDATE CASCADE
		)

		CREATE DATABASE EJER14

		USE EJER14

		CREATE TABLE OBRA (
		ID CHAR(9) Not Null CONSTRAINT PK_OBRA PRIMARY KEY
		)
		CREATE TABLE EDIFICIO (
		NOMBRE VARCHAR(20) Not Null CONSTRAINT PK_EDIFICIO PRIMARY KEY,
		DIRECCION VARCHAR(30)
		)
		CREATE TABLE OFICINA (
		NOMBRE VARCHAR(20),
		NUMERO CHAR(9),
		CONSTRAINT FK_OFICINA_EDIFICIO FOREIGN KEY (NOMBRE) REFERENCES EDIFICIO(NOMBRE),
		CONSTRAINT PK_OFICINA PRIMARY KEY (NOMBRE, NUMERO)
		)
		CREATE TABLE EMPLEADOOFICINISTA (
		DNI CHAR(9),
		NOMBRE VARCHAR(20),
		SUELDO CHAR(5),
		JEFE CHAR(9),
		TITULACION VARCHAR(30),
		NUMERO CHAR(9),
		CONSTRAINT PK_EMPLEADOOFICINISTA PRIMARY KEY (DNI),
		CONSTRAINT FK_EMPLEADOOFICINISTA_EDIFICIO FOREIGN KEY (NOMBRE) REFERENCES EDIFICIO(NOMBRE),
		CONSTRAINT FK_EMPLEADOOFICINISTA_OFICINA FOREIGN KEY (NOMBRE, NUMERO) REFERENCES OFICINA(NOMBRE, NUMERO),
		CONSTRAINT FK_EMPLEADOOFICINISTA_JEFE FOREIGN KEY (JEFE) REFERENCES EMPLEADOOFICINISTA(DNI)
		)
		CREATE TABLE EMPLEADOOBRERO (
		DNI CHAR(9),
		NOMBRE VARCHAR(20),
		SUELDO CHAR(5),
		ID CHAR(9),
		FECHAINICIO DATE,
		JEFE CHAR(9),
		CONSTRAINT PK_EMPLEADOOBRERO PRIMARY KEY (DNI),
		CONSTRAINT FK_EMPLEADOEMPLEADOOBRA_OBRA FOREIGN KEY (ID) REFERENCES OBRA(ID),
		CONSTRAINT FK_EMPLEADOOOBRERO_EMPLEADOOOBRERO FOREIGN KEY (JEFE) REFERENCES EMPLEADOOBRERO(DNI)
		)

		CREATE DATABASE SCRIPT

		USE SCRIPT

		CREATE TABLE CRIATURASRARAS(
		ID tinyint Not NULL,
		Nombre nvarchar(30) Not NULL,
		FechaNac Date NULL, 
		NumeroPie SmallInt NULL,
		NivelIngles NChar(2) NULL,
		Historieta VarChar(300) NULL,
		NumeroChico TinyInt NULL,
		NumeroGrande BigInt NULL,
		NumeroIntermedio SmallInt NULL ,
		Temperatura Decimal(3,1) NULL,
		CONSTRAINT [PK_CriaturitasEx] PRIMARY KEY(ID)
		) 

	ALTER TABLE CRIATURASRARAS
		ADD CONSTRAINT CK_NUMEROGRANDE CHECK(NumeroGrande > 1000*100),
		 CONSTRAINT CK_NUMEROPIE CHECK(NumeroPie BETWEEN 25 AND 60),
		 CONSTRAINT CK_NUMEROCHICO CHECK(NumeroChico < 1000),
		 CONSTRAINT CK_NIVELINGLES CHECK(NivelIngles IN ('A0''A1''A2''B1''B2''C1''C2')),
		 CONSTRAINT CK_HISTORIETA CHECK(Historieta != "OSCURO" AND Historieta != "APOCALIPSIS"),
		 CONSTRAINT CK_NUMEROINTERMEDIO CHECK(NumeroIntermedio % 2 = 0 AND NumeroIntermedio < 1000*100 AND NumeroIntermedio > 1000),
		 CONSTRAINT CK_FECHANACIMIENTO CHECK(FechaNac != CURRENT_TIMESTAMP),
		 CONSTRAINT CK_HISTORIETA CHECK(Historieta <> CONCAT(ID, "Pecadores", NumeroPie)),
		 CONSTRAINT CK_TEMPERATURA CHECK(Temperatura BETWEEN 32.5 AND 44);