-----------TABLA EMPLEADOS----------

CREATE DATABASE Empleados

USE Empleados

CREATE TABLE EMPLEADO (
	DNI VARCHAR(9) Not Null Constraint PKEMPLEADO PRIMARY KEY
	)
CREATE TABLE DEPARTAMENTO (
	NUMDEPAR SMALLINT Not Null Constraint PKDEPARTAMENTO PRIMARY KEY
	)
CREATE TABLE TRABAJA (
	PKDEPARTAMENTO SMALLINT NOT NULL,
    PKEMPLEADO VARCHAR(9) NOT NULL,
    CONSTRAINT PKTRABAJA PRIMARY KEY (PKDEPARTAMENTO, PKEMPLEADO),
    CONSTRAINT FK_TRABAJA_DEPARTAMENTO FOREIGN KEY (PKDEPARTAMENTO) REFERENCES DEPARTAMENTO(NUMDEPAR),
    CONSTRAINT FK_TRABAJA_EMPLEADO FOREIGN KEY (PKEMPLEADO) REFERENCES EMPLEADO(DNI)
	)

	-----------TABLA JUEGA----------

	CREATE DATABASE JUEGA

	USE JUEGA

	CREATE TABLE FUTBOLISTA (
		DNI VARCHAR(9) Not Null Constraint PKFUTBOLISTA PRIMARY KEY
		)
	CREATE TABLE PARTIDO (
		ID SMALLINT Not Null Constraint PKPARTIDO PRIMARY KEY,
		FECHA SmallDateTime Not Null
		)
	create table juega (
		PKFUTBOLISTA VARCHAR(9) NOT NULL,
		PKPARTIDO SMALLINT NOT NULL,
		CONSTRAINT PKJUEGA PRIMARY KEY (PKFUTBOLISTA, PKPARTIDO),
		CONSTRAINT FK_JUEGA_FUTBOLISTA FOREIGN KEY (PKFUTBOLISTA) REFERENCES FUTBOLISTA(DNI),
		CONSTRAINT FK_JUEGA_PARTIDO FOREIGN KEY (PKPARTIDO) REFERENCES PARTIDO(ID)
		)

	-----------TABLA COMPRA----------

	CREATE DATABASE COMPRA

	USE COMPRA

	CREATE TABLE CLIENTE (
	DNI VARCHAR(9) Not Null Constraint PKCLIENTE PRIMARY KEY
	)
	CREATE TABLE TRAJE (
	MODELO SMALLINT Not Null Constraint PKTRAJE PRIMARY KEY
	)
	CREATE TABLE COMPRA (
		PKCLIENTE VARCHAR(9) NOT NULL,
		PKTRAJE SMALLINT NOT NULL,
		CONSTRAINT PKCOMPRA PRIMARY KEY (PKCLIENTE, PKTRAJE),
		CONSTRAINT FK_COMPRA_CLIENTE FOREIGN KEY (PKCLIENTE) REFERENCES CLIENTE(DNI),
		CONSTRAINT FK_COMPRA_TRAJE FOREIGN KEY (PKTRAJE) REFERENCES TRAJE(MODELO)
		)

	-----------TABLA COMPRA----------

	CREATE DATABASE TIENE

	USE TIENE

	CREATE TABLE PERSONA (
	DNI CHAR(9) NOT NULL CONSTRAINT PKPERSONA PRIMARY KEY 
	)
	CREATE TABLE COCHE (
	MATRICULA CHAR(7) NOT NULL CONSTRAINT PKCOCHE PRIMARY KEY,
	COLOR VARCHAR(15) NOT NULL
	)
	CREATE TABLE TIENE (
	PKPERSONA CHAR(9) NOT NULL,
	PKCOCHE CHAR(7),
	CONSTRAINT PKTIENE PRIMARY KEY (PKCOCHE),
	CONSTRAINT FK_TIENE_COCHE FOREIGN KEY (PKCOCHE) REFERENCES COCHE(MATRICULA),
	CONSTRAINT FK_TIENE_PERSONA FOREIGN KEY (PKPERSONA) REFERENCES PERSONA(DNI)
	)

	-----------TABLA POSEE----------

	CREATE DATABASE POSEE

	USE POSEE

	CREATE TABLE PERSONA (
	Dni Char(9) Not Null Constraint PKPERSONA Primary key
	)
	CREATE TABLE COCHE (
	Matricula Char(7) Not Null Constraint PKCOCHE Primary key,
	Color Varchar(15) Not Null
	)
	CREATE TABLE POSEE (
	PKPERSONA Char(9) Not Null,
	PKCOCHE Char(7) Not Null,
	FECHA SmallDateTime Not Null,
	CONSTRAINT FK_POSEE_PERSONA FOREIGN KEY (PKPERSONA) REFERENCES PERSONA(Dni),
	CONSTRAINT FK_POSEE_COCHE FOREIGN KEY (PKCOCHE) REFERENCES COCHE(Matricula)
	)

		-----------TABLA GUARDA----------

	CREATE DATABASE GUARDA

	USE GUARDA

	CREATE TABLE COCHE (
	Matricula char(7) Not Null Constraint PK_COCHE Primary Key
	)
	CREATE TABLE COCHERA (
	Id SmallInt Not Null Constraint PK_COCHERA Primary Key
	)
	CREATE TABLE GUARDA (
	PK_COCHE char(7) Not Null,
	PK_COCHERA SmallInt Not Null,
	CONSTRAINT PK_GUARDA PRIMARY KEY (PK_COCHE),
	CONSTRAINT FK_GUARDA_COCHE FOREIGN KEY (PK_COCHE) REFERENCES COCHE(Matricula),
	CONSTRAINT UQ_GUARDA_COCHERA UNIQUE (PK_COCHERA),
	CONSTRAINT FK_GUARDA_COCHERA FOREIGN KEY (PK_COCHERA) REFERENCES COCHERA(Id)
	)

		-----------TABLA UTILIZA-ESTA----------

		CREATE DATABASE UTILIZA_ESTA

		USE UTILIZA_ESTA

		CREATE TABLE ALUMNO (
		Dni char(9) Constraint PK_ALUMNO Primary Key,
		PK_ORDENADOR SMALLINT NOT NULL,
		Constraint FK_ALUMNO_ORDENADOR FOREIGN KEY (PK_ORDENADOR) REFERENCES ORDENADOR(Id)
		)
		CREATE TABLE ORDENADOR (
		Id SmallInt Constraint PK_ORDENADOR Primary Key,
		PK_AULA SMALLINT NOT NULL,
		Constraint FK_ORDENADOR_AULA FOREIGN KEY (PK_AULA) REFERENCES AULA(Numero)
		)
		CREATE TABLE AULA (
		Numero SmallInt Constraint PK_AULA Primary Key
		)
		
		-----------TABLA UTILIZA-ESTA----------

		CREATE DATABASE UTILIZA_ESTA

		USE UTILIZA_ESTA

		CREATE TABLE ALUMNO (
		Dni char(9) Constraint PK_ALUMNO Primary Key
		)
		CREATE TABLE ORDENADOR (
		Id SmallInt Constraint PK_ORDENADOR Primary Key
		)
		CREATE TABLE AULA (
		Numero Int Constraint PK_AULA Primary Key
		)
		CREATE TABLE UTILIZA (
		Curso SmallInt Constraint PK_UTILIZA Primary Key,
		PK_ALUMNO char(9) CONSTRAINT PK_ALUMNO PRIMARY KEY (PK_ALUMNO),
		PK_ORDENADOR char(9) CONSTRAINT PK_ORDENADOR PRIMARY KEY (PK_ORDENADOR)
		)
		CREATE TABLE ESTA (
		Curso SmallInt Constraint PK_UTILIZA Primary Key,
		PK_ORDENADOR char(9) CONSTRAINT PK_ORDENADOR PRIMARY KEY (PK_ORDENADOR),
		PK_AULA char(9) CONSTRAINT PK_AULA PRIMARY KEY (PK_AULA)
		)

		-----------TABLA UTILIZA-ESTA----------

		CREATE DATABASE UTILIZA

		USE UTILIZA

		CREATE TABLE ALUMNO (
		Dni char(9) Constraint PK_ALUMNO Primary Key
		)
		CREATE TABLE APLICACION (
		Titulo varchar(40) Constraint PK_APLICACION Primary Key
		)
		CREATE TABLE ORDENADOR (
		Id char(9) Constraint PK_ORDENADOR Primary Key
		)
		CREATE TABLE UTILIZA (
		Tiempo VARCHAR(20),
		PK_ALUMNO CHAR(9),
		PK_APLICACION VARCHAR(40),
		FK_ORDENADOR CHAR(9),
		CONSTRAINT PK_UTILIZA PRIMARY KEY (PK_ALUMNO, PK_APLICACION, FK_ORDENADOR),
		CONSTRAINT FK_UTILIZA_ALUMNO FOREIGN KEY (PK_ALUMNO) REFERENCES ALUMNO(Dni),
		CONSTRAINT FK_UTILIZA_APLICACION FOREIGN KEY (PK_APLICACION) REFERENCES APLICACION(Titulo),
		CONSTRAINT FK_UTILIZA_ORDENADOR FOREIGN KEY (FK_ORDENADOR) REFERENCES ORDENADOR(Id)
		)

		-----------TABLA UTILIZA-ESTA----------

		CREATE DATABASE Ej12

		USE Ej12

		CREATE TABLE CONDUCTOR (
		Dni char(9) Not Null Constraint PK_CONDUCTOR Primary Key,
		FK_CALLE VARCHAR(40) CONSTRAINT FK_CALLE_NOMBRE FOREIGN KEY (FK_NOMBRE) REFERENCES CALLE (Nombre)
		)
		CREATE TABLE AUTOBUS (
		Matricula CHAR(9) Not Null Constraint PK_AUTOBUS Primary Key
		)
		CREATE TABLE LINEA (
		Numero CHAR(2) Not Null Constraint PK_AUTOBUS Primary Key
		)
		CREATE TABLE UTILIZA (
		Dia CHAR(2) Not Null Constraint PK_UTILIZA Primary Key,
		CONSTRAINT PK_UTILIZA PRIMARY KEY (PK_ALUMNO, PK_APLICACION, FK_ORDENADOR),
		)
		CREATE TABLE CALLE (
		Nombre VARCHAR(30) Not Null Constraint PK_CALLE Primary Key
		)
		CREATE TABLE PASA (
		Numero CHAR(9),
		Calle VARCHAR(30), 
		CONSTRAINT PK_PASA PRIMARY KEY (PK_LINEA,PK_CALLE),
		CONSTRAINT FK_PASA_LINEA FOREIGN KEY (PK_LINEA) REFERENCES LINEA (Numero),
		CONSTRAINT FK_PASA_CALLE FOREIGN KEY (PK_CALLE) REFERENCES CALLE (Nombre)
		)
